apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  creationTimestamp: null
  name: k0s
spec:
  api:
    address: 10.0.2.15
    k0sApiPort: 9443
    port: 6443
    sans:
    - 10.0.2.15
    - 172.17.0.1
  controllerManager: {}
  images:
    calico:
      cni:
        image: docker.io/calico/cni
        version: v3.18.1
      kubecontrollers:
        image: docker.io/calico/kube-controllers
        version: v3.18.1
      node:
        image: docker.io/calico/node
        version: v3.18.1
    coredns:
      image: docker.io/coredns/coredns
      version: 1.7.0
    default_pull_policy: IfNotPresent
    konnectivity:
      image: us.gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent
      version: v0.0.24
    kubeproxy:
      image: k8s.gcr.io/kube-proxy
      version: v1.22.2
    kuberouter:
      cni:
        image: docker.io/cloudnativelabs/kube-router
        version: v1.3.1
      cniInstaller:
        image: quay.io/k0sproject/cni-node
        version: 0.1.0
    metricsserver:
      image: gcr.io/k8s-staging-metrics-server/metrics-server
      version: v0.5.0
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  konnectivity:
    adminPort: 8133
    agentPort: 8132
  network:
    calico: null
    dualStack: {}
    kubeProxy:
      mode: iptables
    kuberouter:
      autoMTU: true
      mtu: 0
      peerRouterASNs: ""
      peerRouterIPs: ""
    podCIDR: 10.244.0.0/16
    provider: kuberouter
    serviceCIDR: 10.96.0.0/12
  podSecurityPolicy:
    defaultPolicy: 00-k0s-privileged
  scheduler: {}
  storage:
    etcd:
      externalCluster:
        endpoints:
        - https://192.168.10.10:2379
        etcdPrefix: k0s-tenant-2
        caFile: /etc/pki/CA/ca.crt
        clientCertFile: /etc/pki/tls/certs/k0s.crt
        clientKeyFile: /etc/pki/tls/private/k0s.key
    type: etcd
  telemetry:
    enabled: true
status: {}
