# -*- mode: ruby -*-
# vi: set ft=ruby :

ETCD_IP = "192.168.10.10"

Vagrant.configure("2") do |config|

  config.vm.define "etcd" do |node|
    node.vm.provider :virtualbox do |vb|
      vb.memory = 256
      vb.cpus = 1
    end

    node.vm.box = "ubuntu/bionic64"
    node.vm.hostname = "etcd.k0s.sandbox"
    node.vm.network :private_network, ip: ETCD_IP

    node.vm.provision :file, source: "./certs/ca.crt", destination: "/home/vagrant/ca.crt"
    node.vm.provision :file, source: "./certs/etcd.crt", destination: "/home/vagrant/etcd.crt"
    node.vm.provision :file, source: "./private/etcd.key", destination: "/home/vagrant/etcd.key"

    node.vm.provision "install_etcd", type: "shell", path: "../install-etcd.sh"
    node.vm.provision "configure_etcd", type: "shell", env: { "NODE_IP" => ETCD_IP }, inline: <<-SHELL
      # setup TLS keys and certs
      sudo mkdir -p /etc/pki/CA /etc/pki/tls/certs /etc/pki/tls/private
      sudo mv /home/vagrant/ca.crt /etc/pki/CA/ca.crt
      sudo mv /home/vagrant/etcd.crt /etc/pki/tls/certs/etcd.crt
      sudo mv /home/vagrant/etcd.key /etc/pki/tls/private/etcd.key

      # configure etcd as a service
      sudo mkdir /etc/systemd/system/etcd.service.d
      tee -a /etc/systemd/system/etcd.service.d/single-node-cluster.conf <<EOT
[Service]
Environment=ETCD_NAME="single-node"
Environment=ETCD_DATA_DIR="/var/lib/etcd"
Environment=ETCD_ADVERTISE_CLIENT_URLS="https://etcd.k0s.sandbox:2379"
Environment=ETCD_LISTEN_CLIENT_URLS="https://$NODE_IP:2379"
Environment=ETCD_CA_FILE=/etc/pki/CA/ca.crt
Environment=ETCD_CERT_FILE=/etc/pki/tls/certs/etcd.crt
Environment=ETCD_KEY_FILE=/etc/pki/tls/private/etcd.key
EOT
    sudo systemctl enable etcd
    sudo systemctl restart etcd
    SHELL
  end

  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  (1..2).each do |i|
    config.vm.define "k0s-tenant-#{i}" do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "k0s-#{i}.k0s.sandbox"
      node.vm.network :private_network, ip: "192.168.10.#{10+i}"

      node.vm.provision :file, source: "./certs/ca.crt", destination: "/home/vagrant/ca.crt"
      node.vm.provision :file, source: "./certs/k0s-#{i}.crt", destination: "/home/vagrant/k0s.crt"
      node.vm.provision :file, source: "./private/k0s-#{i}.key", destination: "/home/vagrant/k0s.key"

      node.vm.provision :file, source: "../k0s", destination: "/home/vagrant/k0s"
      node.vm.provision :file, source: "./k0s-tenant-#{i}.yaml", destination: "/home/vagrant/k0s.yaml"

      node.vm.provision :shell, inline: <<-SHELL
        # setup TLS keys and certs
        sudo mkdir -p /etc/pki/CA /etc/pki/tls/certs /etc/pki/tls/private
        sudo mv /home/vagrant/ca.crt /etc/pki/CA/ca.crt
        sudo mv /home/vagrant/k0s.crt /etc/pki/tls/certs/k0s.crt
        sudo mv /home/vagrant/k0s.key /etc/pki/tls/private/k0s.key

        # configure k0s as a service
        sudo mv /home/vagrant/k0s /usr/local/bin/k0s
        sudo k0s install controller --single -c /home/vagrant/k0s.yaml
        sudo k0s start
      SHELL
    end
  end

end
