# -*- mode: ruby -*-
# vi: set ft=ruby :

ETCD_IP         = "192.168.1.10"
K0S_SYSTEMD_IP  = "192.168.1.11"
K0S_OPENRC_IP   = "192.168.1.12"

Vagrant.configure("2") do |config|

  config.vm.define "etcd" do |node|
    node.vm.provider :virtualbox do |vb|
      vb.memory = 256
      vb.cpus = 1
    end

    node.vm.box = "ubuntu/bionic64"
    node.vm.hostname = "etcd"
    node.vm.network :private_network, ip: ETCD_IP

    node.vm.provision "install_etcd", type: "shell", path: "../install-etcd.sh"
    node.vm.provision "configure_etcd", type: "shell", env: { "NODE_IP" => ETCD_IP }, inline: <<-SHELL
      sudo mkdir /etc/systemd/system/etcd.service.d
      tee -a /etc/systemd/system/etcd.service.d/single-node-cluster.conf <<EOT
[Service]
Environment=ETCD_NAME="single-node"
Environment=ETCD_DATA_DIR="/var/lib/etcd"
Environment=ETCD_ADVERTISE_CLIENT_URLS="http://$NODE_IP:2379"
Environment=ETCD_LISTEN_CLIENT_URLS="http://$NODE_IP:2379"
EOT
    sudo systemctl enable etcd
    sudo systemctl restart etcd
    SHELL
  end

  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define "k0s-systemd" do |node|
    node.vm.box = "ubuntu/bionic64"
    node.vm.hostname = "k0s-systemd"
    node.vm.network :private_network, ip: K0S_SYSTEMD_IP

    node.vm.provision :file, source: "../k0s", destination: "/home/vagrant/k0s"
    node.vm.provision :file, source: "./k0s-systemd.yaml", destination: "/home/vagrant/k0s.yaml"

    node.vm.provision :shell, inline: <<-SHELL
      sudo mv /home/vagrant/k0s /usr/local/bin/k0s
      sudo k0s install controller --single -c /home/vagrant/k0s.yaml
      sudo k0s start
    SHELL
  end

  config.vm.define "k0s-openrc" do |node|
    node.vm.box = "generic/alpine313"
    node.vm.hostname = "k0s-openrc"
    node.vm.network :private_network, ip: K0S_OPENRC_IP

    node.vm.provision "configure-cgroups", type: "shell", path: "../../common/openrc/configure-cgroups.sh"
    node.vm.provision :file, source: "../k0s", destination: "/home/vagrant/k0s"
    node.vm.provision :file, source: "./k0s-openrc.yaml", destination: "/home/vagrant/k0s.yaml"
    node.vm.provision :shell, inline: <<-SHELL
      sudo mv /home/vagrant/k0s /usr/local/bin/k0s
      sudo k0s install controller --single -c /home/vagrant/k0s.yaml
    SHELL
    node.vm.provision :shell, reboot: true
  end

end
