# -*- mode: ruby -*-
# vi: set ft=ruby :

K0S_DIR = ENV['K0S_DIR']

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.disksize.size = '20GB'

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
  end

  config.vm.synced_folder K0S_DIR, "/home/vagrant/k0s"

  config.vm.provision "install-basic-deps", type: "shell", path: "install-basic-deps.sh"
  config.vm.provision "install-docker",     type: "shell", path: "../common/ubuntu-bionic64/install-docker.sh"
  config.vm.provision "install-footloose",  type: "shell", path: "install-footloose.sh"
  config.vm.provision "install-go",         type: "shell", path: "install-go.sh"
end
